#
# Module manifest for module 'OrionDesign'
#
# Generated by: Sune Alexandersen Narud
#
# Generated on: 2026-08-26
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'OrionDesign.psm1'

# Version number of this module.
ModuleVersion = '3.1.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f827a4ef-a736-449b-b684-dfeba0fdadc3'

# Author of this module
Author = 'Sune Alexandersen Narud'

# Company or vendor of this module
CompanyName = 'Sune Alexandersen Narud'

# Copyright statement for this module
Copyright = '(c) 2026 Sune Alexandersen Narud. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Orion Design Framework - Beautiful PowerShell UI functions for creating rich terminal interfaces. Includes themed output, progress bars, menus, banners, charts, alerts, panels and more. Every function includes a built-in -Demo parameter.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

        PSData = @{

            Tags         = @('UI', 'Terminal', 'Console', 'Output', 'Formatting', 'Theme', 'Menu', 'Banner', 'Chart', 'ProgressBar', 'Colors', 'TUI', 'PowerShell5', 'PSCore')
            ProjectUri   = 'https://github.com/suneworld/OrionDesign'
            LicenseUri   = 'https://github.com/suneworld/OrionDesign/blob/master/LICENSE'
            ReleaseNotes = @'
## v3.1.1
- Fixed not all functions beein available by implementing modules
  using the Sampler Framework.

## v3.1.0
- Added -Demo parameter to all 21 public functions
- Each demo shows live output with exact code that produced it
- Dynamic code box width (auto-sizes to content)
- Added Show-OrionSmartMenu with arrow-key and numeric navigation modes

## v3.0.0
- Restructured module to flat layout
- Renamed Write-MenuLine parameter MenuTitle to Text
- Fixed theme color pairings throughout

## v2.1.4
- Added Write-MenuLine with -Muted parameter
- Enhanced Write-Action/Write-ActionResult alignment
'@
        }

    } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
